name: Go Lang CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: AiGen # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: /home/site/wwwroot/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Install dependencies
        run: go mod download
      - name: Build Go binaries
        run: go build -o ./bin/app
      - name: Building web app
        uses: azure/appservice-build@v2
      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
